use_frameworks!

target 'LYImageFilter_Example' do
  pod 'LYImageFilter', :path => '../'

  target 'LYImageFilter_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
